### ISSUE TITLE
Migrate docs to the main repo

### ISSUE THREAD

**Issue by 0xTim** [vapor/docs-cn#26]
We've [just launched](https://blog.vapor.codes/posts/documentation-changes/) real localisation support for the main documentation site to allow us to support any language required. Could you migrate the translated pages over to their respective pages in the main site, as described [in the README](https://github.com/vapor/docs#translating)?

Once we've done that we can archive this repo and redirect requests to the main docs site

**Comment by Jinxiansen** [comment]
That's great!
I'm glad to see that mkocs is finally supporting i18n, so we don't have to spend time maintaining 2 doc repos.
I will do this tonight and submit the PR to [docs](https://github.com/vapor/docs) once completed.

**Comment by Jinxiansen** [comment]
Hi Tim,
This repo has been migrated to vapor [doc](https://github.com/vapor/docs/pull/664), so it looks like it's ready to be archived now.

In addition, I have a question, how to deal with the update and PR review of the Chinese version in the future?
Because my suggestion is that each country's language has a corresponding reviewer, otherwise non-native speakers may not understand the translated content and will not know whether the translation result is correct.

**Comment by 0xTim** [comment]
@Jinxiansen yes we'll need to work out the best way to do changes. They probably need to be separate PRs as well otherwise people would be required to add translations for languages they can't speak. So I think we could have an action for any PR submitted to the docs that creates an issue to translate the changes in the PR. What do you think?

**Comment by Jinxiansen** [comment]
Agree, thanks!

**Comment by 0xTim** [comment]
Created as https://github.com/vapor/docs/issues/665 to track
